# Generated by Django 4.0.1 on 2022-01-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=34)),
                ('Release_date', models.DateField()),
                ('Movie_starcast', models.CharField(max_length=34)),
                ('Movie_Director', models.CharField(max_length=256)),
            ],
        ),
    ]
