# Generated by Django 4.0.1 on 2022-01-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_movierecord_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierecord',
            name='Movie_poster',
        ),
    ]
