# Generated by Django 4.0.1 on 2022-01-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_movierecord_udata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierecord',
            name='udata',
        ),
    ]
